//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("FacebookToOutlook.Data")]
[assembly: AssemblyCompany("Jake Ginnivan")]
[assembly: AssemblyProduct("FacebookToOutlook")]
[assembly: AssemblyCopyright("Copyright © Jake Ginnivan 2010")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: AssemblyVersion("1.1.0.0")]
[assembly: AssemblyFileVersion("1.1.0.0")]
[assembly: Guid("29f518f8-146f-4c14-9c33-fde85c2ab40b")]


