//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Outlook.Utility")]
[assembly: AssemblyDescription("Outlook Managed Utility Classes")]
[assembly: AssemblyCompany("Jake Ginnivan")]
[assembly: AssemblyProduct("Outlook.Utility")]
[assembly: AssemblyCopyright("Copyright © Jake Ginnivan 2010")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: AssemblyVersion("1.0.2.0")]
[assembly: AssemblyFileVersion("1.0.2.0")]
[assembly: InternalsVisibleTo("Outlook.Utility.Tests")]
[assembly: Guid("7a363628-fe8d-4a9d-8e6a-471eed29001f")]


