//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Office.Utility")]
[assembly: AssemblyDescription("Office Managed Utility Classes")]
[assembly: AssemblyCompany("Jake Ginnivan")]
[assembly: AssemblyProduct("Office.Utility")]
[assembly: AssemblyCopyright("Copyright © Jake Ginnivan 2010")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: AssemblyVersion("1.0.2.0")]
[assembly: AssemblyFileVersion("1.0.2.0")]
[assembly: InternalsVisibleTo("Office.Utility.Tests")]
[assembly: Guid("1e2c00b2-93ae-4041-aed0-c326207c069c")]


